# Generated by Django 3.0.7 on 2020-06-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField(blank=True, null=True)),
                ('dkp', models.IntegerField(blank=True, null=True)),
                ('gp', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('boss', models.CharField(blank=True, max_length=40)),
                ('name', models.TextField(blank=True, null=True)),
                ('ep', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=10)),
                ('dkp', models.IntegerField()),
                ('ep', models.IntegerField()),
                ('gp', models.IntegerField()),
            ],
        ),
    ]
