# Generated by Django 3.0.7 on 2020-06-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='point',
            new_name='score',
        ),
    ]
