# Generated by Django 3.0.7 on 2020-06-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0002_auto_20200620_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField()),
                ('dkp', models.IntegerField()),
                ('gp', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('boss', models.CharField(max_length=40)),
                ('name', models.TextField()),
                ('ep', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='kill',
        ),
        migrations.DeleteModel(
            name='loot',
        ),
    ]
