# Generated by Django 3.0.7 on 2020-06-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='xiaohao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dahao', models.CharField(max_length=20)),
                ('xiaohao', models.CharField(max_length=20)),
            ],
        ),
    ]
