# Generated by Django 3.0.7 on 2020-06-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0003_auto_20200621_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='dkp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ep',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='gp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='item',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
