# Generated by Django 3.0.7 on 2020-06-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0004_xiaohao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='boss',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
