# Generated by Django 3.0.7 on 2020-06-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0005_auto_20200630_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='ep',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='score',
            name='gp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
